FROM node:7.7.2-alpine

WORKDIR /var/www

RUN npm install --quiet
# Для использования в продакшне
# RUN npm install --production

#TODO не работает демон npm
#CMD ["npm", "start"]
#CMD /bin/bash -c 'npm install; npm start'
